using System;
using AutoFixture;
using Xunit;

namespace LfrlAnvil.Mathematical.Expressions.Tests.MathExpressionFactoryTests;

public class MathExpressionFactoryTestsData
{
    public static TheoryData<string, decimal> GetArgumentOnlyData(IFixture fixture)
    {
        return new TheoryData<string, decimal>
        {
            { "a", 0 },
            { "a", 123 },
            { "a", -123 },
            { "( a )", 0 },
            { "( a )", 123 },
            { "( a )", -123 },
            { "( ( ( a ) ) )", 0 },
            { "( ( ( a ) ) )", 123 },
            { "( ( ( a ) ) )", -123 }
        };
    }

    public static TheoryData<string> GetOperandFollowedByOperandData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            "'foobar' 'qux'",
            "'foobar' 12.34",
            "'foobar' false",
            "'foobar' a",
            "12.34 'qux'",
            "12.34 12.34",
            "12.34 false",
            "12.34 a",
            "false 'qux'",
            "false 12.34",
            "false false",
            "false a",
            "a 'qux'",
            "a 12.34",
            "a false",
            "a a"
        };
    }

    public static TheoryData<string> GetOperandFollowedByPrefixUnaryOperatorData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            "'foobar' -",
            "12.34 -",
            "false -",
            "a -"
        };
    }

    public static TheoryData<string> GetOperandFollowedByPrefixTypeConverterData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            "'foobar' [string]",
            "12.34 [string]",
            "false [string]",
            "a [string]"
        };
    }

    public static TheoryData<string> GetOperandFollowedByOpenParenthesisData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            "'foobar' (",
            "12.34 (",
            "false (",
            "a ("
        };
    }

    public static TheoryData<string> GetClosedParenthesisDoesNotHaveCorrespondingOpenParenthesisData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            ")",
            "'foobar' )",
            "12.34 )",
            "false )",
            "a )",
            "( 'foobar' ) )",
            "( 12.34 ) )",
            "( false ) )",
            "( a ) )",
            ")",
            "- 'foobar' )",
            "- 12.34 )",
            "- false )",
            "- a )",
            "'foobar' ^ )",
            "12.34 ^ )",
            "false ^ )",
            "a ^ )",
            "- 'foobar' ^ )",
            "- 12.34 ^ )",
            "- false ^ )",
            "- a ^ )",
            "[string] 'foobar' )",
            "[string] 12.34 )",
            "[string] false )",
            "[string] a )",
            "'foobar' ToString )",
            "12.34 ToString )",
            "false ToString )",
            "a ToString )",
            "'foobar' + 'qux' )",
            "12.34 + 12.34 )",
            "false + true )",
            "a + b )",
        };
    }

    public static TheoryData<string> GetPrefixUnaryConstructIsFollowedByAnotherConstructData(IFixture fixture)
    {
        return new TheoryData<string>
        {
            "- - a",
            "- [string] a",
            "- + a",
            "- ^ a",
            "- ToString a",
            "[string] - a",
            "[string] [string] a",
            "[string] + a",
            "[string] ^ a",
            "[string] ToString a"
        };
    }

    public static TheoryData<string, string[], string> GetMockedSimpleExpressionData(IFixture fixture)
    {
        return new TheoryData<string, string[], string>
        {
            { "- 'foobar'", Array.Empty<string>(), "( PreOp|foobar )" },
            { "- 12.34", Array.Empty<string>(), "( PreOp|12.34 )" },
            { "- false", Array.Empty<string>(), "( PreOp|False )" },
            { "- a", new[] { "foo" }, "( PreOp|foo )" },

            { "[string] 12.34", Array.Empty<string>(), "( PreCast|12.34 )" },
            { "[string] false", Array.Empty<string>(), "( PreCast|False )" },

            { "'foobar' %", Array.Empty<string>(), "( foobar|PostOp )" },
            { "12.34 %", Array.Empty<string>(), "( 12.34|PostOp )" },
            { "false %", Array.Empty<string>(), "( False|PostOp )" },
            { "a %", new[] { "foo" }, "( foo|PostOp )" },

            { "12.34 ToString", Array.Empty<string>(), "( 12.34|PostCast )" },
            { "false ToString", Array.Empty<string>(), "( False|PostCast )" },

            { "- 'foobar' %", Array.Empty<string>(), "( ( PreOp|foobar )|PostOp )" },
            { "- 12.34 %", Array.Empty<string>(), "( ( PreOp|12.34 )|PostOp )" },
            { "- false %", Array.Empty<string>(), "( ( PreOp|False )|PostOp )" },
            { "- a %", new[] { "foo" }, "( ( PreOp|foo )|PostOp )" },

            { "[string] 12.34 %", Array.Empty<string>(), "( ( PreCast|12.34 )|PostOp )" },
            { "[string] false %", Array.Empty<string>(), "( ( PreCast|False )|PostOp )" },

            { "'foobar' + 'qux'", Array.Empty<string>(), "( foobar|BiOp|qux )" },
            { "'foobar' + 12.34", Array.Empty<string>(), "( foobar|BiOp|12.34 )" },
            { "'foobar' + false", Array.Empty<string>(), "( foobar|BiOp|False )" },
            { "'foobar' + a", new[] { "foo" }, "( foobar|BiOp|foo )" },
            { "12.34 + 'qux'", Array.Empty<string>(), "( 12.34|BiOp|qux )" },
            { "12.34 + 12.34", Array.Empty<string>(), "( 12.34|BiOp|12.34 )" },
            { "12.34 + false", Array.Empty<string>(), "( 12.34|BiOp|False )" },
            { "12.34 + a", new[] { "foo" }, "( 12.34|BiOp|foo )" },
            { "false + 'qux'", Array.Empty<string>(), "( False|BiOp|qux )" },
            { "false + 12.34", Array.Empty<string>(), "( False|BiOp|12.34 )" },
            { "false + false", Array.Empty<string>(), "( False|BiOp|False )" },
            { "false + a", new[] { "foo" }, "( False|BiOp|foo )" },
            { "a + 'qux'", new[] { "foo" }, "( foo|BiOp|qux )" },
            { "a + 12.34", new[] { "foo" }, "( foo|BiOp|12.34 )" },
            { "a + false", new[] { "foo" }, "( foo|BiOp|False )" },
            { "a + a", new[] { "foo" }, "( foo|BiOp|foo )" },
            { "a + b", new[] { "foo", "bar" }, "( foo|BiOp|bar )" },

            { "- 'foobar' + 'qux'", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|qux )" },
            { "- 'foobar' + 12.34", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|12.34 )" },
            { "- 'foobar' + false", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|False )" },
            { "- 'foobar' + a", new[] { "foo" }, "( ( PreOp|foobar )|BiOp|foo )" },
            { "- 12.34 + 'qux'", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|qux )" },
            { "- 12.34 + 12.34", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|12.34 )" },
            { "- 12.34 + false", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|False )" },
            { "- 12.34 + a", new[] { "foo" }, "( ( PreOp|12.34 )|BiOp|foo )" },
            { "- false + 'qux'", Array.Empty<string>(), "( ( PreOp|False )|BiOp|qux )" },
            { "- false + 12.34", Array.Empty<string>(), "( ( PreOp|False )|BiOp|12.34 )" },
            { "- false + false", Array.Empty<string>(), "( ( PreOp|False )|BiOp|False )" },
            { "- false + a", new[] { "foo" }, "( ( PreOp|False )|BiOp|foo )" },
            { "- a + 'qux'", new[] { "foo" }, "( ( PreOp|foo )|BiOp|qux )" },
            { "- a + 12.34", new[] { "foo" }, "( ( PreOp|foo )|BiOp|12.34 )" },
            { "- a + false", new[] { "foo" }, "( ( PreOp|foo )|BiOp|False )" },
            { "- a + a", new[] { "foo" }, "( ( PreOp|foo )|BiOp|foo )" },
            { "- a + b", new[] { "foo", "bar" }, "( ( PreOp|foo )|BiOp|bar )" },

            { "- 'foobar' % + 'qux'", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|qux )" },
            { "- 'foobar' % + 12.34", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|12.34 )" },
            { "- 'foobar' % + false", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|False )" },
            { "- 'foobar' % + a", new[] { "foo" }, "( ( ( PreOp|foobar )|PostOp )|BiOp|foo )" },
            { "- 12.34 % + 'qux'", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|qux )" },
            { "- 12.34 % + 12.34", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|12.34 )" },
            { "- 12.34 % + false", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|False )" },
            { "- 12.34 % + a", new[] { "foo" }, "( ( ( PreOp|12.34 )|PostOp )|BiOp|foo )" },
            { "- false % + 'qux'", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|qux )" },
            { "- false % + 12.34", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|12.34 )" },
            { "- false % + false", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|False )" },
            { "- false % + a", new[] { "foo" }, "( ( ( PreOp|False )|PostOp )|BiOp|foo )" },
            { "- a % + 'qux'", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|qux )" },
            { "- a % + 12.34", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|12.34 )" },
            { "- a % + false", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|False )" },
            { "- a % + a", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|foo )" },
            { "- a % + b", new[] { "foo", "bar" }, "( ( ( PreOp|foo )|PostOp )|BiOp|bar )" },

            { "'foobar' + - 'qux'", Array.Empty<string>(), "( foobar|BiOp|( PreOp|qux ) )" },
            { "'foobar' + - 12.34", Array.Empty<string>(), "( foobar|BiOp|( PreOp|12.34 ) )" },
            { "'foobar' + - false", Array.Empty<string>(), "( foobar|BiOp|( PreOp|False ) )" },
            { "'foobar' + - a", new[] { "foo" }, "( foobar|BiOp|( PreOp|foo ) )" },
            { "12.34 + - 'qux'", Array.Empty<string>(), "( 12.34|BiOp|( PreOp|qux ) )" },
            { "12.34 + - 12.34", Array.Empty<string>(), "( 12.34|BiOp|( PreOp|12.34 ) )" },
            { "12.34 + - false", Array.Empty<string>(), "( 12.34|BiOp|( PreOp|False ) )" },
            { "12.34 + - a", new[] { "foo" }, "( 12.34|BiOp|( PreOp|foo ) )" },
            { "false + - 'qux'", Array.Empty<string>(), "( False|BiOp|( PreOp|qux ) )" },
            { "false + - 12.34", Array.Empty<string>(), "( False|BiOp|( PreOp|12.34 ) )" },
            { "false + - false", Array.Empty<string>(), "( False|BiOp|( PreOp|False ) )" },
            { "false + - a", new[] { "foo" }, "( False|BiOp|( PreOp|foo ) )" },
            { "a + - 'qux'", new[] { "foo" }, "( foo|BiOp|( PreOp|qux ) )" },
            { "a + - 12.34", new[] { "foo" }, "( foo|BiOp|( PreOp|12.34 ) )" },
            { "a + - false", new[] { "foo" }, "( foo|BiOp|( PreOp|False ) )" },
            { "a + - a", new[] { "foo" }, "( foo|BiOp|( PreOp|foo ) )" },
            { "a + - b", new[] { "foo", "bar" }, "( foo|BiOp|( PreOp|bar ) )" },

            { "- 'foobar' + - 'qux'", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( PreOp|qux ) )" },
            { "- 'foobar' + - 12.34", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( PreOp|12.34 ) )" },
            { "- 'foobar' + - false", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( PreOp|False ) )" },
            { "- 'foobar' + - a", new[] { "foo" }, "( ( PreOp|foobar )|BiOp|( PreOp|foo ) )" },
            { "- 12.34 + - 'qux'", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( PreOp|qux ) )" },
            { "- 12.34 + - 12.34", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( PreOp|12.34 ) )" },
            { "- 12.34 + - false", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( PreOp|False ) )" },
            { "- 12.34 + - a", new[] { "foo" }, "( ( PreOp|12.34 )|BiOp|( PreOp|foo ) )" },
            { "- false + - 'qux'", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( PreOp|qux ) )" },
            { "- false + - 12.34", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( PreOp|12.34 ) )" },
            { "- false + - false", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( PreOp|False ) )" },
            { "- false + - a", new[] { "foo" }, "( ( PreOp|False )|BiOp|( PreOp|foo ) )" },
            { "- a + - 'qux'", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( PreOp|qux ) )" },
            { "- a + - 12.34", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( PreOp|12.34 ) )" },
            { "- a + - false", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( PreOp|False ) )" },
            { "- a + - a", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( PreOp|foo ) )" },
            { "- a + - b", new[] { "foo", "bar" }, "( ( PreOp|foo )|BiOp|( PreOp|bar ) )" },

            { "- 'foobar' % + - 'qux'", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( PreOp|qux ) )" },
            { "- 'foobar' % + - 12.34", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( PreOp|12.34 ) )" },
            { "- 'foobar' % + - false", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( PreOp|False ) )" },
            { "- 'foobar' % + - a", new[] { "foo" }, "( ( ( PreOp|foobar )|PostOp )|BiOp|( PreOp|foo ) )" },
            { "- 12.34 % + - 'qux'", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( PreOp|qux ) )" },
            { "- 12.34 % + - 12.34", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( PreOp|12.34 ) )" },
            { "- 12.34 % + - false", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( PreOp|False ) )" },
            { "- 12.34 % + - a", new[] { "foo" }, "( ( ( PreOp|12.34 )|PostOp )|BiOp|( PreOp|foo ) )" },
            { "- false % + - 'qux'", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( PreOp|qux ) )" },
            { "- false % + - 12.34", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( PreOp|12.34 ) )" },
            { "- false % + - false", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( PreOp|False ) )" },
            { "- false % + - a", new[] { "foo" }, "( ( ( PreOp|False )|PostOp )|BiOp|( PreOp|foo ) )" },
            { "- a % + - 'qux'", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( PreOp|qux ) )" },
            { "- a % + - 12.34", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( PreOp|12.34 ) )" },
            { "- a % + - false", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( PreOp|False ) )" },
            { "- a % + - a", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( PreOp|foo ) )" },
            { "- a % + - b", new[] { "foo", "bar" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( PreOp|bar ) )" },

            { "'foobar' + - 'qux' %", Array.Empty<string>(), "( foobar|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "'foobar' + - 12.34 %", Array.Empty<string>(), "( foobar|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "'foobar' + - false %", Array.Empty<string>(), "( foobar|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "'foobar' + - a %", new[] { "foo" }, "( foobar|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "12.34 + - 'qux' %", Array.Empty<string>(), "( 12.34|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "12.34 + - 12.34 %", Array.Empty<string>(), "( 12.34|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "12.34 + - false %", Array.Empty<string>(), "( 12.34|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "12.34 + - a %", new[] { "foo" }, "( 12.34|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "false + - 'qux' %", Array.Empty<string>(), "( False|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "false + - 12.34 %", Array.Empty<string>(), "( False|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "false + - false %", Array.Empty<string>(), "( False|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "false + - a %", new[] { "foo" }, "( False|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "a + - 'qux' %", new[] { "foo" }, "( foo|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "a + - 12.34 %", new[] { "foo" }, "( foo|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "a + - false %", new[] { "foo" }, "( foo|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "a + - a %", new[] { "foo" }, "( foo|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "a + - b %", new[] { "foo", "bar" }, "( foo|BiOp|( ( PreOp|bar )|PostOp ) )" },

            { "- 'foobar' + - 'qux' %", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- 'foobar' + - 12.34 %", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- 'foobar' + - false %", Array.Empty<string>(), "( ( PreOp|foobar )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- 'foobar' + - a %", new[] { "foo" }, "( ( PreOp|foobar )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- 12.34 + - 'qux' %", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- 12.34 + - 12.34 %", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- 12.34 + - false %", Array.Empty<string>(), "( ( PreOp|12.34 )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- 12.34 + - a %", new[] { "foo" }, "( ( PreOp|12.34 )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- false + - 'qux' %", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- false + - 12.34 %", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- false + - false %", Array.Empty<string>(), "( ( PreOp|False )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- false + - a %", new[] { "foo" }, "( ( PreOp|False )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- a + - 'qux' %", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- a + - 12.34 %", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- a + - false %", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- a + - a %", new[] { "foo" }, "( ( PreOp|foo )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- a + - b %", new[] { "foo", "bar" }, "( ( PreOp|foo )|BiOp|( ( PreOp|bar )|PostOp ) )" },

            { "- 'foobar' % + - 'qux' %", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- 'foobar' % + - 12.34 %", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- 'foobar' % + - false %", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- 'foobar' % + - a %", new[] { "foo" }, "( ( ( PreOp|foobar )|PostOp )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- 12.34 % + - 'qux' %", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- 12.34 % + - 12.34 %", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- 12.34 % + - false %", Array.Empty<string>(), "( ( ( PreOp|12.34 )|PostOp )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- 12.34 % + - a %", new[] { "foo" }, "( ( ( PreOp|12.34 )|PostOp )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- false % + - 'qux' %", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- false % + - 12.34 %", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- false % + - false %", Array.Empty<string>(), "( ( ( PreOp|False )|PostOp )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- false % + - a %", new[] { "foo" }, "( ( ( PreOp|False )|PostOp )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- a % + - 'qux' %", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( ( PreOp|qux )|PostOp ) )" },
            { "- a % + - 12.34 %", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( ( PreOp|12.34 )|PostOp ) )" },
            { "- a % + - false %", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( ( PreOp|False )|PostOp ) )" },
            { "- a % + - a %", new[] { "foo" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( ( PreOp|foo )|PostOp ) )" },
            { "- a % + - b %", new[] { "foo", "bar" }, "( ( ( PreOp|foo )|PostOp )|BiOp|( ( PreOp|bar )|PostOp ) )" },

            { "- ( 'foobar' )", Array.Empty<string>(), "( PreOp|foobar )" },
            { "( 'foobar' ) %", Array.Empty<string>(), "( foobar|PostOp )" },
            { "- ( 'foobar' ) %", Array.Empty<string>(), "( ( PreOp|foobar )|PostOp )" },
            { "- ( - 'foobar' )", Array.Empty<string>(), "( PreOp|( PreOp|foobar ) )" },
            { "( - 'foobar' ) %", Array.Empty<string>(), "( ( PreOp|foobar )|PostOp )" },
            { "- ( - 'foobar' ) %", Array.Empty<string>(), "( ( PreOp|( PreOp|foobar ) )|PostOp )" },
            { "- ( 'foobar' % )", Array.Empty<string>(), "( PreOp|( foobar|PostOp ) )" },
            { "( 'foobar' % ) %", Array.Empty<string>(), "( ( foobar|PostOp )|PostOp )" },
            { "- ( 'foobar' % ) %", Array.Empty<string>(), "( ( PreOp|( foobar|PostOp ) )|PostOp )" },
            { "- ( - 'foobar' % )", Array.Empty<string>(), "( PreOp|( ( PreOp|foobar )|PostOp ) )" },
            { "( - 'foobar' % ) %", Array.Empty<string>(), "( ( ( PreOp|foobar )|PostOp )|PostOp )" },
            { "- ( - 'foobar' % ) %", Array.Empty<string>(), "( ( PreOp|( ( PreOp|foobar )|PostOp ) )|PostOp )" },
            { "( 'foo' + 'bar' )", Array.Empty<string>(), "( foo|BiOp|bar )" },
            { "- ( 'foo' + 'bar' )", Array.Empty<string>(), "( PreOp|( foo|BiOp|bar ) )" },
            { "( 'foo' + 'bar' ) %", Array.Empty<string>(), "( ( foo|BiOp|bar )|PostOp )" },
            { "- ( 'foo' + 'bar' ) %", Array.Empty<string>(), "( ( PreOp|( foo|BiOp|bar ) )|PostOp )" }
        };
    }

    public static TheoryData<string, string> GetMockedExpressionWithDifferencesInPrecedenceData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "- 12.34 %", "( ( PreNegOp|12.34 )|PostPerOp )" },
            { "- 12.34 !", "( PreNegOp|( 12.34|PostExclOp ) )" },
            { "- 12.34 ToString", "( PreNegOp|( 12.34|PostCast ) )" },
            { "^ 12.34 %", "( ( PreCaretOp|12.34 )|PostPerOp )" },
            { "^ 12.34 !", "( ( PreCaretOp|12.34 )|PostExclOp )" },
            { "[string] 12.34 %", "( ( PreCast|12.34 )|PostPerOp )" },
            { "[string] 12.34 !", "( ( PreCast|12.34 )|PostExclOp )" },

            { "'foo' + 'bar' + 'qux'", "( ( foo|BiAddOp|bar )|BiAddOp|qux )" },
            { "( 'foo' + 'bar' ) + 'qux'", "( ( foo|BiAddOp|bar )|BiAddOp|qux )" },
            { "'foo' + ( 'bar' + 'qux' )", "( foo|BiAddOp|( bar|BiAddOp|qux ) )" },
            { "'foo' * 'bar' + 'qux'", "( ( foo|BiMultOp|bar )|BiAddOp|qux )" },
            { "( 'foo' * 'bar' ) + 'qux'", "( ( foo|BiMultOp|bar )|BiAddOp|qux )" },
            { "'foo' * ( 'bar' + 'qux' )", "( foo|BiMultOp|( bar|BiAddOp|qux ) )" },
            { "'foo' + 'bar' * 'qux'", "( foo|BiAddOp|( bar|BiMultOp|qux ) )" },
            { "( 'foo' + 'bar' ) * 'qux'", "( ( foo|BiAddOp|bar )|BiMultOp|qux )" },
            { "'foo' + ( 'bar' * 'qux' )", "( foo|BiAddOp|( bar|BiMultOp|qux ) )" },

            { "'foo' + 'bar' + 'qux' + 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( 'foo' + 'bar' ) + 'qux' + 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "'foo' + ( 'bar' + 'qux' ) + 'abc'", "( ( foo|BiAddOp|( bar|BiAddOp|qux ) )|BiAddOp|abc )" },
            { "'foo' + 'bar' + ( 'qux' + 'abc' )", "( ( foo|BiAddOp|bar )|BiAddOp|( qux|BiAddOp|abc ) )" },
            { "( 'foo' + 'bar' + 'qux' ) + 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( ( 'foo' + 'bar' ) + 'qux' ) + 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( 'foo' + ( 'bar' + 'qux' ) ) + 'abc'", "( ( foo|BiAddOp|( bar|BiAddOp|qux ) )|BiAddOp|abc )" },
            { "'foo' + ( 'bar' + 'qux' + 'abc' )", "( foo|BiAddOp|( ( bar|BiAddOp|qux )|BiAddOp|abc ) )" },
            { "'foo' + ( ( 'bar' + 'qux' ) + 'abc' )", "( foo|BiAddOp|( ( bar|BiAddOp|qux )|BiAddOp|abc ) )" },
            { "'foo' + ( 'bar' + ( 'qux' + 'abc' ) )", "( foo|BiAddOp|( bar|BiAddOp|( qux|BiAddOp|abc ) ) )" },

            { "'foo' * 'bar' + 'qux' + 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( 'foo' * 'bar' ) + 'qux' + 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "'foo' * ( 'bar' + 'qux' ) + 'abc'", "( ( foo|BiMultOp|( bar|BiAddOp|qux ) )|BiAddOp|abc )" },
            { "'foo' * 'bar' + ( 'qux' + 'abc' )", "( ( foo|BiMultOp|bar )|BiAddOp|( qux|BiAddOp|abc ) )" },
            { "( 'foo' * 'bar' + 'qux' ) + 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( ( 'foo' * 'bar' ) + 'qux' ) + 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiAddOp|abc )" },
            { "( 'foo' * ( 'bar' + 'qux' ) ) + 'abc'", "( ( foo|BiMultOp|( bar|BiAddOp|qux ) )|BiAddOp|abc )" },
            { "'foo' * ( 'bar' + 'qux' + 'abc' )", "( foo|BiMultOp|( ( bar|BiAddOp|qux )|BiAddOp|abc ) )" },
            { "'foo' * ( ( 'bar' + 'qux' ) + 'abc' )", "( foo|BiMultOp|( ( bar|BiAddOp|qux )|BiAddOp|abc ) )" },
            { "'foo' * ( 'bar' + ( 'qux' + 'abc' ) )", "( foo|BiMultOp|( bar|BiAddOp|( qux|BiAddOp|abc ) ) )" },

            { "'foo' + 'bar' * 'qux' + 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "( 'foo' + 'bar' ) * 'qux' + 'abc'", "( ( ( foo|BiAddOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "'foo' + ( 'bar' * 'qux' ) + 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "'foo' + 'bar' * ( 'qux' + 'abc' )", "( foo|BiAddOp|( bar|BiMultOp|( qux|BiAddOp|abc ) ) )" },
            { "( 'foo' + 'bar' * 'qux' ) + 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "( ( 'foo' + 'bar' ) * 'qux' ) + 'abc'", "( ( ( foo|BiAddOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "( 'foo' + ( 'bar' * 'qux' ) ) + 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "'foo' + ( 'bar' * 'qux' + 'abc' )", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiAddOp|abc ) )" },
            { "'foo' + ( ( 'bar' * 'qux' ) + 'abc' )", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiAddOp|abc ) )" },
            { "'foo' + ( 'bar' * ( 'qux' + 'abc' ) )", "( foo|BiAddOp|( bar|BiMultOp|( qux|BiAddOp|abc ) ) )" },

            { "'foo' + 'bar' + 'qux' * 'abc'", "( ( foo|BiAddOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "( 'foo' + 'bar' ) + 'qux' * 'abc'", "( ( foo|BiAddOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "'foo' + ( 'bar' + 'qux' ) * 'abc'", "( foo|BiAddOp|( ( bar|BiAddOp|qux )|BiMultOp|abc ) )" },
            { "'foo' + 'bar' + ( 'qux' * 'abc' )", "( ( foo|BiAddOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "( 'foo' + 'bar' + 'qux' ) * 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiMultOp|abc )" },
            { "( ( 'foo' + 'bar' ) + 'qux' ) * 'abc'", "( ( ( foo|BiAddOp|bar )|BiAddOp|qux )|BiMultOp|abc )" },
            { "( 'foo' + ( 'bar' + 'qux' ) ) * 'abc'", "( ( foo|BiAddOp|( bar|BiAddOp|qux ) )|BiMultOp|abc )" },
            { "'foo' + ( 'bar' + 'qux' * 'abc' )", "( foo|BiAddOp|( bar|BiAddOp|( qux|BiMultOp|abc ) ) )" },
            { "'foo' + ( ( 'bar' + 'qux' ) * 'abc' )", "( foo|BiAddOp|( ( bar|BiAddOp|qux )|BiMultOp|abc ) )" },
            { "'foo' + ( 'bar' + ( 'qux' * 'abc' ) )", "( foo|BiAddOp|( bar|BiAddOp|( qux|BiMultOp|abc ) ) )" },

            { "'foo' * 'bar' * 'qux' + 'abc'", "( ( ( foo|BiMultOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "( 'foo' * 'bar' ) * 'qux' + 'abc'", "( ( ( foo|BiMultOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "'foo' * ( 'bar' * 'qux' ) + 'abc'", "( ( foo|BiMultOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "'foo' * 'bar' * ( 'qux' + 'abc' )", "( ( foo|BiMultOp|bar )|BiMultOp|( qux|BiAddOp|abc ) )" },
            { "( 'foo' * 'bar' * 'qux' ) + 'abc'", "( ( ( foo|BiMultOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "( ( 'foo' * 'bar' ) * 'qux' ) + 'abc'", "( ( ( foo|BiMultOp|bar )|BiMultOp|qux )|BiAddOp|abc )" },
            { "( 'foo' * ( 'bar' * 'qux' ) ) + 'abc'", "( ( foo|BiMultOp|( bar|BiMultOp|qux ) )|BiAddOp|abc )" },
            { "'foo' * ( 'bar' * 'qux' + 'abc' )", "( foo|BiMultOp|( ( bar|BiMultOp|qux )|BiAddOp|abc ) )" },
            { "'foo' * ( ( 'bar' * 'qux' ) + 'abc' )", "( foo|BiMultOp|( ( bar|BiMultOp|qux )|BiAddOp|abc ) )" },
            { "'foo' * ( 'bar' * ( 'qux' + 'abc' ) )", "( foo|BiMultOp|( bar|BiMultOp|( qux|BiAddOp|abc ) ) )" },

            { "'foo' + 'bar' * 'qux' * 'abc'", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiMultOp|abc ) )" },
            { "( 'foo' + 'bar' ) * 'qux' * 'abc'", "( ( ( foo|BiAddOp|bar )|BiMultOp|qux )|BiMultOp|abc )" },
            { "'foo' + ( 'bar' * 'qux' ) * 'abc'", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiMultOp|abc ) )" },
            { "'foo' + 'bar' * ( 'qux' * 'abc' )", "( foo|BiAddOp|( bar|BiMultOp|( qux|BiMultOp|abc ) ) )" },
            { "( 'foo' + 'bar' * 'qux' ) * 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiMultOp|abc )" },
            { "( ( 'foo' + 'bar' ) * 'qux' ) * 'abc'", "( ( ( foo|BiAddOp|bar )|BiMultOp|qux )|BiMultOp|abc )" },
            { "( 'foo' + ( 'bar' * 'qux' ) ) * 'abc'", "( ( foo|BiAddOp|( bar|BiMultOp|qux ) )|BiMultOp|abc )" },
            { "'foo' + ( 'bar' * 'qux' * 'abc' )", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiMultOp|abc ) )" },
            { "'foo' + ( ( 'bar' * 'qux' ) * 'abc' )", "( foo|BiAddOp|( ( bar|BiMultOp|qux )|BiMultOp|abc ) )" },
            { "'foo' + ( 'bar' * ( 'qux' * 'abc' ) )", "( foo|BiAddOp|( bar|BiMultOp|( qux|BiMultOp|abc ) ) )" },

            { "'foo' * 'bar' + 'qux' * 'abc'", "( ( foo|BiMultOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "( 'foo' * 'bar' ) + 'qux' * 'abc'", "( ( foo|BiMultOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "'foo' * ( 'bar' + 'qux' ) * 'abc'", "( ( foo|BiMultOp|( bar|BiAddOp|qux ) )|BiMultOp|abc )" },
            { "'foo' * 'bar' + ( 'qux' * 'abc' )", "( ( foo|BiMultOp|bar )|BiAddOp|( qux|BiMultOp|abc ) )" },
            { "( 'foo' * 'bar' + 'qux' ) * 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiMultOp|abc )" },
            { "( ( 'foo' * 'bar' ) + 'qux' ) * 'abc'", "( ( ( foo|BiMultOp|bar )|BiAddOp|qux )|BiMultOp|abc )" },
            { "( 'foo' * ( 'bar' + 'qux' ) ) * 'abc'", "( ( foo|BiMultOp|( bar|BiAddOp|qux ) )|BiMultOp|abc )" },
            { "'foo' * ( 'bar' + 'qux' * 'abc' )", "( foo|BiMultOp|( bar|BiAddOp|( qux|BiMultOp|abc ) ) )" },
            { "'foo' * ( ( 'bar' + 'qux' ) * 'abc' )", "( foo|BiMultOp|( ( bar|BiAddOp|qux )|BiMultOp|abc ) )" },
            { "'foo' * ( 'bar' + ( 'qux' * 'abc' ) )", "( foo|BiMultOp|( bar|BiAddOp|( qux|BiMultOp|abc ) ) )" }
        };
    }

    public static TheoryData<string, string[], string> GetMockedExpressionWithOperatorAmbiguityData(IFixture fixture)
    {
        //  PRE  BIN  POS
        //   ^
        //        /
        //             !
        //   *    *
        //        +    +
        //   %         %
        //   -    -    -
        return new TheoryData<string, string[], string>
        {
            { "^ 'foo'", Array.Empty<string>(), "( PreCaretOp|foo )" },
            { "* 'foo'", Array.Empty<string>(), "( PreRefOp|foo )" },
            { "% 'foo'", Array.Empty<string>(), "( PrePerOp|foo )" },
            { "- 'foo'", Array.Empty<string>(), "( PreNegOp|foo )" },
            { "'foo' !", Array.Empty<string>(), "( foo|PostExclOp )" },
            { "'foo' +", Array.Empty<string>(), "( foo|PostPlusOp )" },
            { "'foo' %", Array.Empty<string>(), "( foo|PostPerOp )" },
            { "'foo' -", Array.Empty<string>(), "( foo|PostNegOp )" },

            { "( ^ 'foo' )", Array.Empty<string>(), "( PreCaretOp|foo )" },
            { "( * 'foo' )", Array.Empty<string>(), "( PreRefOp|foo )" },
            { "( % 'foo' )", Array.Empty<string>(), "( PrePerOp|foo )" },
            { "( - 'foo' )", Array.Empty<string>(), "( PreNegOp|foo )" },
            { "( 'foo' ! )", Array.Empty<string>(), "( foo|PostExclOp )" },
            { "( 'foo' + )", Array.Empty<string>(), "( foo|PostPlusOp )" },
            { "( 'foo' % )", Array.Empty<string>(), "( foo|PostPerOp )" },
            { "( 'foo' - )", Array.Empty<string>(), "( foo|PostNegOp )" },

            { "'foo' / 'bar'", Array.Empty<string>(), "( foo|BiDivOp|bar )" },
            { "'foo' / ^ 'bar'", Array.Empty<string>(), "( foo|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' / * 'bar'", Array.Empty<string>(), "( foo|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' / % 'bar'", Array.Empty<string>(), "( foo|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' / - 'bar'", Array.Empty<string>(), "( foo|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' ! / 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|bar )" },
            { "'foo' ! / ^ 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' ! / * 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' ! / % 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' ! / - 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' + / 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|bar )" },
            { "'foo' + / ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' + / * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' + / % 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' + / - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' % / 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|bar )" },
            { "'foo' % / ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' % / * 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' % / % 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' % / - 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' - / 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|bar )" },
            { "'foo' - / ^ 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' - / * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' - / % 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' - / - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreNegOp|bar ) )" },

            { "'foo' * 'bar'", Array.Empty<string>(), "( foo|BiMultOp|bar )" },
            { "'foo' * ^ 'bar'", Array.Empty<string>(), "( foo|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' * * 'bar'", Array.Empty<string>(), "( foo|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' * % 'bar'", Array.Empty<string>(), "( foo|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' * - 'bar'", Array.Empty<string>(), "( foo|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' ! * 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|bar )" },
            { "'foo' ! * ^ 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' ! * * 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' ! * % 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' ! * - 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' + * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + * ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' + * * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' + * % 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' + * - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' % * 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|bar )" },
            { "'foo' % * ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' % * * 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' % * % 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' % * - 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' - * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - * ^ 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' - * * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' - * % 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' - * - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreNegOp|bar ) )" },

            { "'foo' + 'bar'", Array.Empty<string>(), "( foo|BiAddOp|bar )" },
            { "'foo' + ^ 'bar'", Array.Empty<string>(), "( foo|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + % 'bar'", Array.Empty<string>(), "( foo|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' ! + 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|bar )" },
            { "'foo' ! + ^ 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' ! + * 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' ! + % 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' ! + - 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' + + 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|bar )" },
            { "'foo' + + ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + + * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' + + % 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + + - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' % + 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|bar )" },
            { "'foo' % + ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' % + * 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' % + % 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' % + - 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' - + 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|bar )" },
            { "'foo' - + ^ 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' - + * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' - + % 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' - + - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreNegOp|bar ) )" },

            { "'foo' - 'bar'", Array.Empty<string>(), "( foo|BiSubOp|bar )" },
            { "'foo' - ^ 'bar'", Array.Empty<string>(), "( foo|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - % 'bar'", Array.Empty<string>(), "( foo|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' ! - 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|bar )" },
            { "'foo' ! - ^ 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' ! - * 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' ! - % 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' ! - - 'bar'", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' + - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' + - ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' + - * 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' + - % 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' + - - 'bar'", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' % - 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|bar )" },
            { "'foo' % - ^ 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' % - * 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' % - % 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' % - - 'bar'", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' - - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' - - ^ 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - - * 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' - - % 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - - 'bar'", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreNegOp|bar ) )" },

            { "'foo' / 12.34", Array.Empty<string>(), "( foo|BiDivOp|12.34 )" },
            { "'foo' / ^ 12.34", Array.Empty<string>(), "( foo|BiDivOp|( PreCaretOp|12.34 ) )" },
            { "'foo' / * 12.34", Array.Empty<string>(), "( foo|BiDivOp|( PreRefOp|12.34 ) )" },
            { "'foo' / % 12.34", Array.Empty<string>(), "( foo|BiDivOp|( PrePerOp|12.34 ) )" },
            { "'foo' / - 12.34", Array.Empty<string>(), "( foo|BiDivOp|( PreNegOp|12.34 ) )" },
            { "'foo' ! / 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|12.34 )" },
            { "'foo' ! / ^ 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreCaretOp|12.34 ) )" },
            { "'foo' ! / * 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreRefOp|12.34 ) )" },
            { "'foo' ! / % 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PrePerOp|12.34 ) )" },
            { "'foo' ! / - 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreNegOp|12.34 ) )" },
            { "'foo' + / 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|12.34 )" },
            { "'foo' + / ^ 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreCaretOp|12.34 ) )" },
            { "'foo' + / * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreRefOp|12.34 ) )" },
            { "'foo' + / % 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PrePerOp|12.34 ) )" },
            { "'foo' + / - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreNegOp|12.34 ) )" },
            { "'foo' % / 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|12.34 )" },
            { "'foo' % / ^ 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreCaretOp|12.34 ) )" },
            { "'foo' % / * 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreRefOp|12.34 ) )" },
            { "'foo' % / % 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PrePerOp|12.34 ) )" },
            { "'foo' % / - 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreNegOp|12.34 ) )" },
            { "'foo' - / 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|12.34 )" },
            { "'foo' - / ^ 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreCaretOp|12.34 ) )" },
            { "'foo' - / * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreRefOp|12.34 ) )" },
            { "'foo' - / % 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PrePerOp|12.34 ) )" },
            { "'foo' - / - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreNegOp|12.34 ) )" },

            { "'foo' * 12.34", Array.Empty<string>(), "( foo|BiMultOp|12.34 )" },
            { "'foo' * ^ 12.34", Array.Empty<string>(), "( foo|BiMultOp|( PreCaretOp|12.34 ) )" },
            { "'foo' * * 12.34", Array.Empty<string>(), "( foo|BiMultOp|( PreRefOp|12.34 ) )" },
            { "'foo' * % 12.34", Array.Empty<string>(), "( foo|BiMultOp|( PrePerOp|12.34 ) )" },
            { "'foo' * - 12.34", Array.Empty<string>(), "( foo|BiMultOp|( PreNegOp|12.34 ) )" },
            { "'foo' ! * 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|12.34 )" },
            { "'foo' ! * ^ 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreCaretOp|12.34 ) )" },
            { "'foo' ! * * 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreRefOp|12.34 ) )" },
            { "'foo' ! * % 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PrePerOp|12.34 ) )" },
            { "'foo' ! * - 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreNegOp|12.34 ) )" },
            { "'foo' + * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|12.34 )" },
            { "'foo' + * ^ 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreCaretOp|12.34 ) )" },
            { "'foo' + * * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreRefOp|12.34 ) )" },
            { "'foo' + * % 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PrePerOp|12.34 ) )" },
            { "'foo' + * - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreNegOp|12.34 ) )" },
            { "'foo' % * 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|12.34 )" },
            { "'foo' % * ^ 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreCaretOp|12.34 ) )" },
            { "'foo' % * * 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreRefOp|12.34 ) )" },
            { "'foo' % * % 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PrePerOp|12.34 ) )" },
            { "'foo' % * - 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreNegOp|12.34 ) )" },
            { "'foo' - * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|12.34 )" },
            { "'foo' - * ^ 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreCaretOp|12.34 ) )" },
            { "'foo' - * * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreRefOp|12.34 ) )" },
            { "'foo' - * % 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PrePerOp|12.34 ) )" },
            { "'foo' - * - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreNegOp|12.34 ) )" },

            { "'foo' + 12.34", Array.Empty<string>(), "( foo|BiAddOp|12.34 )" },
            { "'foo' + ^ 12.34", Array.Empty<string>(), "( foo|BiAddOp|( PreCaretOp|12.34 ) )" },
            { "'foo' + * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|12.34 )" },
            { "'foo' + % 12.34", Array.Empty<string>(), "( foo|BiAddOp|( PrePerOp|12.34 ) )" },
            { "'foo' + - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|12.34 )" },
            { "'foo' ! + 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|12.34 )" },
            { "'foo' ! + ^ 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreCaretOp|12.34 ) )" },
            { "'foo' ! + * 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreRefOp|12.34 ) )" },
            { "'foo' ! + % 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PrePerOp|12.34 ) )" },
            { "'foo' ! + - 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreNegOp|12.34 ) )" },
            { "'foo' + + 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|12.34 )" },
            { "'foo' + + ^ 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreCaretOp|12.34 ) )" },
            { "'foo' + + * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreRefOp|12.34 ) )" },
            { "'foo' + + % 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PrePerOp|12.34 ) )" },
            { "'foo' + + - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreNegOp|12.34 ) )" },
            { "'foo' % + 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|12.34 )" },
            { "'foo' % + ^ 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreCaretOp|12.34 ) )" },
            { "'foo' % + * 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreRefOp|12.34 ) )" },
            { "'foo' % + % 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PrePerOp|12.34 ) )" },
            { "'foo' % + - 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreNegOp|12.34 ) )" },
            { "'foo' - + 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|12.34 )" },
            { "'foo' - + ^ 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreCaretOp|12.34 ) )" },
            { "'foo' - + * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreRefOp|12.34 ) )" },
            { "'foo' - + % 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PrePerOp|12.34 ) )" },
            { "'foo' - + - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreNegOp|12.34 ) )" },

            { "'foo' - 12.34", Array.Empty<string>(), "( foo|BiSubOp|12.34 )" },
            { "'foo' - ^ 12.34", Array.Empty<string>(), "( foo|BiSubOp|( PreCaretOp|12.34 ) )" },
            { "'foo' - * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|12.34 )" },
            { "'foo' - % 12.34", Array.Empty<string>(), "( foo|BiSubOp|( PrePerOp|12.34 ) )" },
            { "'foo' - - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|12.34 )" },
            { "'foo' ! - 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|12.34 )" },
            { "'foo' ! - ^ 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreCaretOp|12.34 ) )" },
            { "'foo' ! - * 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreRefOp|12.34 ) )" },
            { "'foo' ! - % 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PrePerOp|12.34 ) )" },
            { "'foo' ! - - 12.34", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreNegOp|12.34 ) )" },
            { "'foo' + - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|12.34 )" },
            { "'foo' + - ^ 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreCaretOp|12.34 ) )" },
            { "'foo' + - * 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreRefOp|12.34 ) )" },
            { "'foo' + - % 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PrePerOp|12.34 ) )" },
            { "'foo' + - - 12.34", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreNegOp|12.34 ) )" },
            { "'foo' % - 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|12.34 )" },
            { "'foo' % - ^ 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreCaretOp|12.34 ) )" },
            { "'foo' % - * 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreRefOp|12.34 ) )" },
            { "'foo' % - % 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PrePerOp|12.34 ) )" },
            { "'foo' % - - 12.34", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreNegOp|12.34 ) )" },
            { "'foo' - - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|12.34 )" },
            { "'foo' - - ^ 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreCaretOp|12.34 ) )" },
            { "'foo' - - * 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreRefOp|12.34 ) )" },
            { "'foo' - - % 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PrePerOp|12.34 ) )" },
            { "'foo' - - - 12.34", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreNegOp|12.34 ) )" },

            { "'foo' / false", Array.Empty<string>(), "( foo|BiDivOp|False )" },
            { "'foo' / ^ false", Array.Empty<string>(), "( foo|BiDivOp|( PreCaretOp|False ) )" },
            { "'foo' / * false", Array.Empty<string>(), "( foo|BiDivOp|( PreRefOp|False ) )" },
            { "'foo' / % false", Array.Empty<string>(), "( foo|BiDivOp|( PrePerOp|False ) )" },
            { "'foo' / - false", Array.Empty<string>(), "( foo|BiDivOp|( PreNegOp|False ) )" },
            { "'foo' ! / false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|False )" },
            { "'foo' ! / ^ false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreCaretOp|False ) )" },
            { "'foo' ! / * false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreRefOp|False ) )" },
            { "'foo' ! / % false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PrePerOp|False ) )" },
            { "'foo' ! / - false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreNegOp|False ) )" },
            { "'foo' + / false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|False )" },
            { "'foo' + / ^ false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreCaretOp|False ) )" },
            { "'foo' + / * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreRefOp|False ) )" },
            { "'foo' + / % false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PrePerOp|False ) )" },
            { "'foo' + / - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreNegOp|False ) )" },
            { "'foo' % / false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|False )" },
            { "'foo' % / ^ false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreCaretOp|False ) )" },
            { "'foo' % / * false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreRefOp|False ) )" },
            { "'foo' % / % false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PrePerOp|False ) )" },
            { "'foo' % / - false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreNegOp|False ) )" },
            { "'foo' - / false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|False )" },
            { "'foo' - / ^ false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreCaretOp|False ) )" },
            { "'foo' - / * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreRefOp|False ) )" },
            { "'foo' - / % false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PrePerOp|False ) )" },
            { "'foo' - / - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreNegOp|False ) )" },

            { "'foo' * false", Array.Empty<string>(), "( foo|BiMultOp|False )" },
            { "'foo' * ^ false", Array.Empty<string>(), "( foo|BiMultOp|( PreCaretOp|False ) )" },
            { "'foo' * * false", Array.Empty<string>(), "( foo|BiMultOp|( PreRefOp|False ) )" },
            { "'foo' * % false", Array.Empty<string>(), "( foo|BiMultOp|( PrePerOp|False ) )" },
            { "'foo' * - false", Array.Empty<string>(), "( foo|BiMultOp|( PreNegOp|False ) )" },
            { "'foo' ! * false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|False )" },
            { "'foo' ! * ^ false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreCaretOp|False ) )" },
            { "'foo' ! * * false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreRefOp|False ) )" },
            { "'foo' ! * % false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PrePerOp|False ) )" },
            { "'foo' ! * - false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreNegOp|False ) )" },
            { "'foo' + * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|False )" },
            { "'foo' + * ^ false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreCaretOp|False ) )" },
            { "'foo' + * * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreRefOp|False ) )" },
            { "'foo' + * % false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PrePerOp|False ) )" },
            { "'foo' + * - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreNegOp|False ) )" },
            { "'foo' % * false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|False )" },
            { "'foo' % * ^ false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreCaretOp|False ) )" },
            { "'foo' % * * false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreRefOp|False ) )" },
            { "'foo' % * % false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PrePerOp|False ) )" },
            { "'foo' % * - false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreNegOp|False ) )" },
            { "'foo' - * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|False )" },
            { "'foo' - * ^ false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreCaretOp|False ) )" },
            { "'foo' - * * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreRefOp|False ) )" },
            { "'foo' - * % false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PrePerOp|False ) )" },
            { "'foo' - * - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreNegOp|False ) )" },

            { "'foo' + false", Array.Empty<string>(), "( foo|BiAddOp|False )" },
            { "'foo' + ^ false", Array.Empty<string>(), "( foo|BiAddOp|( PreCaretOp|False ) )" },
            { "'foo' + * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|False )" },
            { "'foo' + % false", Array.Empty<string>(), "( foo|BiAddOp|( PrePerOp|False ) )" },
            { "'foo' + - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|False )" },
            { "'foo' ! + false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|False )" },
            { "'foo' ! + ^ false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreCaretOp|False ) )" },
            { "'foo' ! + * false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreRefOp|False ) )" },
            { "'foo' ! + % false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PrePerOp|False ) )" },
            { "'foo' ! + - false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreNegOp|False ) )" },
            { "'foo' + + false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|False )" },
            { "'foo' + + ^ false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreCaretOp|False ) )" },
            { "'foo' + + * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreRefOp|False ) )" },
            { "'foo' + + % false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PrePerOp|False ) )" },
            { "'foo' + + - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreNegOp|False ) )" },
            { "'foo' % + false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|False )" },
            { "'foo' % + ^ false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreCaretOp|False ) )" },
            { "'foo' % + * false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreRefOp|False ) )" },
            { "'foo' % + % false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PrePerOp|False ) )" },
            { "'foo' % + - false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreNegOp|False ) )" },
            { "'foo' - + false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|False )" },
            { "'foo' - + ^ false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreCaretOp|False ) )" },
            { "'foo' - + * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreRefOp|False ) )" },
            { "'foo' - + % false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PrePerOp|False ) )" },
            { "'foo' - + - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreNegOp|False ) )" },

            { "'foo' - false", Array.Empty<string>(), "( foo|BiSubOp|False )" },
            { "'foo' - ^ false", Array.Empty<string>(), "( foo|BiSubOp|( PreCaretOp|False ) )" },
            { "'foo' - * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|False )" },
            { "'foo' - % false", Array.Empty<string>(), "( foo|BiSubOp|( PrePerOp|False ) )" },
            { "'foo' - - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|False )" },
            { "'foo' ! - false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|False )" },
            { "'foo' ! - ^ false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreCaretOp|False ) )" },
            { "'foo' ! - * false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreRefOp|False ) )" },
            { "'foo' ! - % false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PrePerOp|False ) )" },
            { "'foo' ! - - false", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreNegOp|False ) )" },
            { "'foo' + - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|False )" },
            { "'foo' + - ^ false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreCaretOp|False ) )" },
            { "'foo' + - * false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreRefOp|False ) )" },
            { "'foo' + - % false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PrePerOp|False ) )" },
            { "'foo' + - - false", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreNegOp|False ) )" },
            { "'foo' % - false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|False )" },
            { "'foo' % - ^ false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreCaretOp|False ) )" },
            { "'foo' % - * false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreRefOp|False ) )" },
            { "'foo' % - % false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PrePerOp|False ) )" },
            { "'foo' % - - false", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreNegOp|False ) )" },
            { "'foo' - - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|False )" },
            { "'foo' - - ^ false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreCaretOp|False ) )" },
            { "'foo' - - * false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreRefOp|False ) )" },
            { "'foo' - - % false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PrePerOp|False ) )" },
            { "'foo' - - - false", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreNegOp|False ) )" },

            { "'foo' / ( 'bar' )", Array.Empty<string>(), "( foo|BiDivOp|bar )" },
            { "'foo' / ^ ( 'bar' )", Array.Empty<string>(), "( foo|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' / * ( 'bar' )", Array.Empty<string>(), "( foo|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' / % ( 'bar' )", Array.Empty<string>(), "( foo|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' / - ( 'bar' )", Array.Empty<string>(), "( foo|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' ! / ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|bar )" },
            { "'foo' ! / ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' ! / * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' ! / % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' ! / - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' + / ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|bar )" },
            { "'foo' + / ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' + / * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' + / % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' + / - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' % / ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|bar )" },
            { "'foo' % / ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' % / * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' % / % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' % / - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' - / ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|bar )" },
            { "'foo' - / ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' - / * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' - / % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' - / - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiDivOp|( PreNegOp|bar ) )" },

            { "'foo' * ( 'bar' )", Array.Empty<string>(), "( foo|BiMultOp|bar )" },
            { "'foo' * ^ ( 'bar' )", Array.Empty<string>(), "( foo|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' * * ( 'bar' )", Array.Empty<string>(), "( foo|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' * % ( 'bar' )", Array.Empty<string>(), "( foo|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' * - ( 'bar' )", Array.Empty<string>(), "( foo|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' ! * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|bar )" },
            { "'foo' ! * ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' ! * * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' ! * % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' ! * - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + * ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' + * * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' + * % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' + * - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' % * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|bar )" },
            { "'foo' % * ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' % * * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' % * % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' % * - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - * ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' - * * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' - * % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' - * - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|( PreNegOp|bar ) )" },

            { "'foo' + ( 'bar' )", Array.Empty<string>(), "( foo|BiAddOp|bar )" },
            { "'foo' + ^ ( 'bar' )", Array.Empty<string>(), "( foo|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + % ( 'bar' )", Array.Empty<string>(), "( foo|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' ! + ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|bar )" },
            { "'foo' ! + ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' ! + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' ! + % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' ! + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' + + ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|bar )" },
            { "'foo' + + ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' + + % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' % + ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|bar )" },
            { "'foo' % + ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' % + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' % + % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' % + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' - + ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|bar )" },
            { "'foo' - + ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' - + * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' - + % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' - + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiAddOp|( PreNegOp|bar ) )" },

            { "'foo' - ( 'bar' )", Array.Empty<string>(), "( foo|BiSubOp|bar )" },
            { "'foo' - ^ ( 'bar' )", Array.Empty<string>(), "( foo|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - % ( 'bar' )", Array.Empty<string>(), "( foo|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' ! - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|bar )" },
            { "'foo' ! - ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' ! - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' ! - % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' ! - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostExclOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' + - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' + - ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' + - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' + - % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' + - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPlusOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' % - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|bar )" },
            { "'foo' % - ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' % - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' % - % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' % - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostPerOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' - - ^ ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - - * ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' - - % ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - - ( 'bar' )", Array.Empty<string>(), "( ( foo|PostNegOp )|BiSubOp|( PreNegOp|bar ) )" },

            { "'foo' / a", new[] { "bar" }, "( foo|BiDivOp|bar )" },
            { "'foo' / ^ a", new[] { "bar" }, "( foo|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' / * a", new[] { "bar" }, "( foo|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' / % a", new[] { "bar" }, "( foo|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' / - a", new[] { "bar" }, "( foo|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' ! / a", new[] { "bar" }, "( ( foo|PostExclOp )|BiDivOp|bar )" },
            { "'foo' ! / ^ a", new[] { "bar" }, "( ( foo|PostExclOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' ! / * a", new[] { "bar" }, "( ( foo|PostExclOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' ! / % a", new[] { "bar" }, "( ( foo|PostExclOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' ! / - a", new[] { "bar" }, "( ( foo|PostExclOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' + / a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiDivOp|bar )" },
            { "'foo' + / ^ a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' + / * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' + / % a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' + / - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' % / a", new[] { "bar" }, "( ( foo|PostPerOp )|BiDivOp|bar )" },
            { "'foo' % / ^ a", new[] { "bar" }, "( ( foo|PostPerOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' % / * a", new[] { "bar" }, "( ( foo|PostPerOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' % / % a", new[] { "bar" }, "( ( foo|PostPerOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' % / - a", new[] { "bar" }, "( ( foo|PostPerOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "'foo' - / a", new[] { "bar" }, "( ( foo|PostNegOp )|BiDivOp|bar )" },
            { "'foo' - / ^ a", new[] { "bar" }, "( ( foo|PostNegOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "'foo' - / * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "'foo' - / % a", new[] { "bar" }, "( ( foo|PostNegOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "'foo' - / - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiDivOp|( PreNegOp|bar ) )" },

            { "'foo' * a", new[] { "bar" }, "( foo|BiMultOp|bar )" },
            { "'foo' * ^ a", new[] { "bar" }, "( foo|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' * * a", new[] { "bar" }, "( foo|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' * % a", new[] { "bar" }, "( foo|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' * - a", new[] { "bar" }, "( foo|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' ! * a", new[] { "bar" }, "( ( foo|PostExclOp )|BiMultOp|bar )" },
            { "'foo' ! * ^ a", new[] { "bar" }, "( ( foo|PostExclOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' ! * * a", new[] { "bar" }, "( ( foo|PostExclOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' ! * % a", new[] { "bar" }, "( ( foo|PostExclOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' ! * - a", new[] { "bar" }, "( ( foo|PostExclOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' + * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + * ^ a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' + * * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' + * % a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' + * - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' % * a", new[] { "bar" }, "( ( foo|PostPerOp )|BiMultOp|bar )" },
            { "'foo' % * ^ a", new[] { "bar" }, "( ( foo|PostPerOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' % * * a", new[] { "bar" }, "( ( foo|PostPerOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' % * % a", new[] { "bar" }, "( ( foo|PostPerOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' % * - a", new[] { "bar" }, "( ( foo|PostPerOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "'foo' - * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - * ^ a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "'foo' - * * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "'foo' - * % a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "'foo' - * - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|( PreNegOp|bar ) )" },

            { "'foo' + a", new[] { "bar" }, "( foo|BiAddOp|bar )" },
            { "'foo' + ^ a", new[] { "bar" }, "( foo|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiMultOp|bar )" },
            { "'foo' + % a", new[] { "bar" }, "( foo|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' ! + a", new[] { "bar" }, "( ( foo|PostExclOp )|BiAddOp|bar )" },
            { "'foo' ! + ^ a", new[] { "bar" }, "( ( foo|PostExclOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' ! + * a", new[] { "bar" }, "( ( foo|PostExclOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' ! + % a", new[] { "bar" }, "( ( foo|PostExclOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' ! + - a", new[] { "bar" }, "( ( foo|PostExclOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' + + a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiAddOp|bar )" },
            { "'foo' + + ^ a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' + + * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' + + % a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' + + - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' % + a", new[] { "bar" }, "( ( foo|PostPerOp )|BiAddOp|bar )" },
            { "'foo' % + ^ a", new[] { "bar" }, "( ( foo|PostPerOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' % + * a", new[] { "bar" }, "( ( foo|PostPerOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' % + % a", new[] { "bar" }, "( ( foo|PostPerOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' % + - a", new[] { "bar" }, "( ( foo|PostPerOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "'foo' - + a", new[] { "bar" }, "( ( foo|PostNegOp )|BiAddOp|bar )" },
            { "'foo' - + ^ a", new[] { "bar" }, "( ( foo|PostNegOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "'foo' - + * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "'foo' - + % a", new[] { "bar" }, "( ( foo|PostNegOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "'foo' - + - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiAddOp|( PreNegOp|bar ) )" },

            { "'foo' - a", new[] { "bar" }, "( foo|BiSubOp|bar )" },
            { "'foo' - ^ a", new[] { "bar" }, "( foo|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiMultOp|bar )" },
            { "'foo' - % a", new[] { "bar" }, "( foo|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' ! - a", new[] { "bar" }, "( ( foo|PostExclOp )|BiSubOp|bar )" },
            { "'foo' ! - ^ a", new[] { "bar" }, "( ( foo|PostExclOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' ! - * a", new[] { "bar" }, "( ( foo|PostExclOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' ! - % a", new[] { "bar" }, "( ( foo|PostExclOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' ! - - a", new[] { "bar" }, "( ( foo|PostExclOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' + - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|bar )" },
            { "'foo' + - ^ a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' + - * a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' + - % a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' + - - a", new[] { "bar" }, "( ( foo|PostPlusOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' % - a", new[] { "bar" }, "( ( foo|PostPerOp )|BiSubOp|bar )" },
            { "'foo' % - ^ a", new[] { "bar" }, "( ( foo|PostPerOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' % - * a", new[] { "bar" }, "( ( foo|PostPerOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' % - % a", new[] { "bar" }, "( ( foo|PostPerOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' % - - a", new[] { "bar" }, "( ( foo|PostPerOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "'foo' - - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|bar )" },
            { "'foo' - - ^ a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "'foo' - - * a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "'foo' - - % a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "'foo' - - - a", new[] { "bar" }, "( ( foo|PostNegOp )|BiSubOp|( PreNegOp|bar ) )" },

            { "- 'foo' / 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiDivOp|bar )" },
            { "- 'foo' / ^ 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiDivOp|( PreCaretOp|bar ) )" },
            { "- 'foo' / * 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiDivOp|( PreRefOp|bar ) )" },
            { "- 'foo' / % 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiDivOp|( PrePerOp|bar ) )" },
            { "- 'foo' / - 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiDivOp|( PreNegOp|bar ) )" },
            { "- 'foo' ! / 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiDivOp|bar )" },
            { "- 'foo' ! / ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "- 'foo' ! / * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "- 'foo' ! / % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "- 'foo' ! / - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "- 'foo' + / 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiDivOp|bar )" },
            { "- 'foo' + / ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "- 'foo' + / * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "- 'foo' + / % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "- 'foo' + / - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "- 'foo' % / 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiDivOp|bar )" },
            { "- 'foo' % / ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "- 'foo' % / * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "- 'foo' % / % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "- 'foo' % / - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiDivOp|( PreNegOp|bar ) )" },
            { "- 'foo' - / 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiDivOp|bar )" },
            { "- 'foo' - / ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiDivOp|( PreCaretOp|bar ) )" },
            { "- 'foo' - / * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiDivOp|( PreRefOp|bar ) )" },
            { "- 'foo' - / % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiDivOp|( PrePerOp|bar ) )" },
            { "- 'foo' - / - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiDivOp|( PreNegOp|bar ) )" },

            { "- 'foo' * 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiMultOp|bar )" },
            { "- 'foo' * ^ 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiMultOp|( PreCaretOp|bar ) )" },
            { "- 'foo' * * 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiMultOp|( PreRefOp|bar ) )" },
            { "- 'foo' * % 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiMultOp|( PrePerOp|bar ) )" },
            { "- 'foo' * - 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiMultOp|( PreNegOp|bar ) )" },
            { "- 'foo' ! * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiMultOp|bar )" },
            { "- 'foo' ! * ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "- 'foo' ! * * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "- 'foo' ! * % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "- 'foo' ! * - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "- 'foo' + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|bar )" },
            { "- 'foo' + * ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "- 'foo' + * * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "- 'foo' + * % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "- 'foo' + * - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "- 'foo' % * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiMultOp|bar )" },
            { "- 'foo' % * ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "- 'foo' % * * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "- 'foo' % * % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "- 'foo' % * - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiMultOp|( PreNegOp|bar ) )" },
            { "- 'foo' - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|bar )" },
            { "- 'foo' - * ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|( PreCaretOp|bar ) )" },
            { "- 'foo' - * * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|( PreRefOp|bar ) )" },
            { "- 'foo' - * % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|( PrePerOp|bar ) )" },
            { "- 'foo' - * - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|( PreNegOp|bar ) )" },

            { "- 'foo' + 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiAddOp|bar )" },
            { "- 'foo' + ^ 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiAddOp|( PreCaretOp|bar ) )" },
            { "- 'foo' + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiMultOp|bar )" },
            { "- 'foo' + % 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiAddOp|( PrePerOp|bar ) )" },
            { "- 'foo' + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|bar )" },
            { "- 'foo' ! + 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiAddOp|bar )" },
            { "- 'foo' ! + ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "- 'foo' ! + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "- 'foo' ! + % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "- 'foo' ! + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "- 'foo' + + 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiAddOp|bar )" },
            { "- 'foo' + + ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "- 'foo' + + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "- 'foo' + + % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "- 'foo' + + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "- 'foo' % + 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiAddOp|bar )" },
            { "- 'foo' % + ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "- 'foo' % + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "- 'foo' % + % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "- 'foo' % + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiAddOp|( PreNegOp|bar ) )" },
            { "- 'foo' - + 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiAddOp|bar )" },
            { "- 'foo' - + ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiAddOp|( PreCaretOp|bar ) )" },
            { "- 'foo' - + * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiAddOp|( PreRefOp|bar ) )" },
            { "- 'foo' - + % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiAddOp|( PrePerOp|bar ) )" },
            { "- 'foo' - + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiAddOp|( PreNegOp|bar ) )" },

            { "- 'foo' - 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiSubOp|bar )" },
            { "- 'foo' - ^ 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiSubOp|( PreCaretOp|bar ) )" },
            { "- 'foo' - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiMultOp|bar )" },
            { "- 'foo' - % 'bar'", Array.Empty<string>(), "( ( PreNegOp|foo )|BiSubOp|( PrePerOp|bar ) )" },
            { "- 'foo' - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|bar )" },
            { "- 'foo' ! - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiSubOp|bar )" },
            { "- 'foo' ! - ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "- 'foo' ! - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "- 'foo' ! - % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "- 'foo' ! - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostExclOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "- 'foo' + - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|bar )" },
            { "- 'foo' + - ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "- 'foo' + - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "- 'foo' + - % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "- 'foo' + - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPlusOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "- 'foo' % - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiSubOp|bar )" },
            { "- 'foo' % - ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "- 'foo' % - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "- 'foo' % - % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "- 'foo' % - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostPerOp )|BiSubOp|( PreNegOp|bar ) )" },
            { "- 'foo' - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|bar )" },
            { "- 'foo' - - ^ 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|( PreCaretOp|bar ) )" },
            { "- 'foo' - - * 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|( PreRefOp|bar ) )" },
            { "- 'foo' - - % 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|( PrePerOp|bar ) )" },
            { "- 'foo' - - - 'bar'", Array.Empty<string>(), "( ( ( PreNegOp|foo )|PostNegOp )|BiSubOp|( PreNegOp|bar ) )" }
        };
    }

    public static TheoryData<string, string> GetCorrectBinaryOperatorSpecializationsData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "'foo' + 'bar'", "( foo|BiOp|bar )" },
            { "'foo' + 12.34", "( foo|BiStringDecimalOp|12.34 )" },
            { "12.34 + 'foo'", "( 12.34|BiDecimalStringOp|foo )" },
            { "12.34 + 12.34", "( 12.34|BiDecimalDecimalOp|12.34 )" }
        };
    }

    public static TheoryData<string, string> GetCorrectPrefixUnaryOperatorSpecializationsData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "- 'foo'", "( PreOp|foo )" },
            { "- 12.34", "( PreDecimalOp|12.34 )" }
        };
    }

    public static TheoryData<string, string> GetCorrectPrefixTypeConverterSpecializationsData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "[string] false", "( PreCast|False )" },
            { "[string] 12.34", "( PreDecimalCast|12.34 )" }
        };
    }

    public static TheoryData<string, string> GetCorrectPostfixUnaryOperatorSpecializationsData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "'foo' ^", "( foo|PostOp )" },
            { "12.34 ^", "( 12.34|PostDecimalOp )" }
        };
    }

    public static TheoryData<string, string> GetCorrectPostfixTypeConverterSpecializationsData(IFixture fixture)
    {
        return new TheoryData<string, string>
        {
            { "false ToString", "( False|PostCast )" },
            { "12.34 ToString", "( 12.34|PostDecimalCast )" }
        };
    }
}
