namespace LfrlAnvil.Computable.Expressions.Errors;

public enum ParsedExpressionBuilderErrorType : byte
{
    Error = 0,
    UnexpectedOperand = 1,
    UnexpectedDelegateParameterName = 2,
    UnexpectedFunctionCall = 3,
    UnexpectedTypeDeclaration = 4,
    UnexpectedConstruct = 5,
    UnexpectedElementSeparator = 6,
    UnexpectedOpenedParenthesis = 7,
    UnexpectedClosedParenthesis = 8,
    UnexpectedOpenedSquareBracket = 9,
    UnexpectedClosedSquareBracket = 10,
    UnexpectedMemberAccess = 11,
    UnexpectedVariableDeclaration = 12,
    UnexpectedAssignment = 13,
    UnexpectedLineSeparator = 14,
    UnexpectedEnd = 15,
    UndeclaredVariableUsage = 16,
    NumberConstantParsingFailure = 17,
    StringConstantParsingFailure = 18,
    InvalidArgumentName = 19,
    InvalidDelegateParameterName = 20,
    InvalidVariableName = 21,
    DuplicatedDelegateParameterName = 22,
    DuplicatedVariableName = 23,
    ConstructHasThrownException = 24,
    ExpressionMustContainAtLeastOneOperand = 25,
    ExpressionContainsInvalidOperandToOperatorRatio = 26,
    MissingSubExpressionClosingSymbol = 27,
    ExpressionContainsUnclosedParentheses = 28,
    UnclosedParenthesis = 29,
    OutputTypeConverterHasThrownException = 30,
    ExpressionResultTypeIsNotCompatibleWithExpectedOutputType = 31,
    PrefixUnaryOperatorCouldNotBeResolved = 32,
    PostfixUnaryOperatorCouldNotBeResolved = 33,
    PrefixTypeConverterCouldNotBeResolved = 34,
    PostfixTypeConverterCouldNotBeResolved = 35,
    BinaryOperatorCouldNotBeResolved = 36,
    FunctionCouldNotBeResolved = 37,
    ExpectedPrefixUnaryConstruct = 38,
    ExpectedBinaryOperator = 39,
    ExpectedPostfixUnaryOrBinaryConstruct = 40,
    ExpectedBinaryOrPrefixUnaryConstruct = 41,
    AmbiguousPostfixUnaryConstructResolutionFailure = 42,
    NestedExpressionFailure = 43,
    InlineDelegateError = 44,
    LocalTermError = 45
}
