namespace LfrlAnvil.Computable.Expressions.Errors;

public enum ParsedExpressionBuilderErrorType : byte
{
    Error = 0,
    UnexpectedOperand = 1,
    UnexpectedFunctionCall = 2,
    UnexpectedTypeDeclaration = 3,
    UnexpectedConstruct = 4,
    UnexpectedElementSeparator = 5,
    NumberConstantParsingFailure = 6,
    StringConstantParsingFailure = 7,
    InvalidArgumentName = 8,
    UnexpectedOpenedParenthesis = 9,
    UnexpectedClosedParenthesis = 10,
    ConstructHasThrownException = 11,
    ExpressionMustContainAtLeastOneOperand = 12,
    ExpressionContainsInvalidOperandToOperatorRatio = 13,
    MissingSubExpressionClosingSymbol = 14,
    ExpressionContainsUnclosedParentheses = 15,
    UnclosedParenthesis = 16,
    OutputTypeConverterHasThrownException = 17,
    ExpressionResultTypeIsNotCompatibleWithExpectedOutputType = 18,
    PrefixUnaryOperatorCouldNotBeResolved = 19,
    PostfixUnaryOperatorCouldNotBeResolved = 20,
    PrefixTypeConverterCouldNotBeResolved = 21,
    PostfixTypeConverterCouldNotBeResolved = 22,
    BinaryOperatorCouldNotBeResolved = 23,
    FunctionCouldNotBeResolved = 24,
    ExpectedPrefixUnaryConstruct = 25,
    ExpectedBinaryOperator = 26,
    ExpectedPostfixUnaryOrBinaryConstruct = 27,
    ExpectedBinaryOrPrefixUnaryConstruct = 28,
    AmbiguousPostfixUnaryConstructResolutionFailure = 29,
    NestedExpressionFailure = 30
}
