name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Cake tool
        run: dotnet tool install --global Cake.Tool --version 4.0.0

      - name: Install dependencies
        run: dotnet restore

      - name: Install tool dependencies
        run: dotnet tool restore

      - name: Run build script
        run: dotnet cake ./scripts/build.cake --target="Publish" --publish-output="publish" --cover-tests=true

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./publish

      - name: Publish test coverage report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: .coverlet/coverage.info
          format: lcov
