name: Deploy static content to Pages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - run: dotnet tool install --global docfx --version 2.75.3

      - name: Install Cake tool
        run: dotnet tool install --global Cake.Tool --version 4.0.0

      - name: Install tool dependencies
        run: dotnet tool restore

      - name: Run docfx script
        run: dotnet cake ./scripts/docfx.cake

      - run: docfx .docfx/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.docfx/_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
